# Lecture 3, Part 1
*(based on materials by Tomasz Krzywicki, PhD Eng.)*

## Working with the NumPy library

The first step when working with NumPy is to import it. We can do this with the command **import numpy**. We can also add an alias, which is a shorter name used in the code when calling functions from the library:

In [1]:
import numpy as np  # we import numpy as np, so later we can use np instead of the full name (run with Shift + Enter)

### Creating new arrays from lists

The simplest way to create a NumPy array is to pass a list of values to the `array` function from NumPy:

In [2]:
# an array of type np.ndarray created from a regular Python list
# in np.ndarray we do not write the element type like List[int] - we just say it is a NumPy array
arr: np.ndarray = np.array([1, 2, 3, 4, 5])

print(arr)  # print the array
print(type(arr))  # print the type of this variable - it is a NumPy array (np.ndarray)
arr

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

We can also create multidimensional arrays (tensors) in a similar way. To do this, we pass a multidimensional list to the `array` function from NumPy.

In [4]:
arr_2d: np.ndarray = np.array([  # we create a matrix from a 2D Python list, so we get a 2D NumPy array
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
])

arr_2d  # if this is the last expression in the cell, we do not need print in Jupyter

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Data types in NumPy

Data types in NumPy describe what kind of values are stored in arrays. The type can be chosen automatically or set manually (for example, to save memory) using the `dtype` parameter.

In [5]:
# here we create an array and say that its values should be of type int
# otherwise NumPy will choose the type automatically, and it may not always be the best choice
arr_int: np.ndarray = np.array([1, 2, 3, 4, 5], dtype='i')

arr_int

array([1, 2, 3, 4, 5], dtype=int32)

We can check the type of values stored in the array using the `dtype` attribute.

In [6]:
arr_int.dtype  # again, no print is needed in Jupyter - this shows the type of values stored in the array

dtype('int32')

### Basic data types in NumPy

Some basic data types in NumPy are:
- `i` - integer
- `b` - boolean
- `u` - unsigned integer (integer >= 0)
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object (any object)
- `S` - string (text)
- `U` - unicode string
- `V` - fixed chunk of memory for another type

### More specific data types in NumPy

In a data type we can also specify how much memory should be reserved for a value. For example, `i4` means a 4-byte integer type.

In [7]:
arr: np.ndarray = np.array([1, 2, 3, 4, 5], dtype='i4')  # array created from a Python list

print(arr)  # print the array
print(arr.dtype)  # print the type of values stored in the array

[1 2 3 4 5]
int32


### Creating arrays with NumPy functions

NumPy also lets us create arrays already filled with values.
The `zeros` function creates arrays of a given size filled with zeros:


In [8]:
np.zeros(10, dtype='i')  # the function returns an array, so we do not need to save it to a variable now - Jupyter will display it

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

We can also use the `zeros` function to create multidimensional arrays:

In [9]:
np.zeros((5, 5))  # if we have more than 1 dimension, we give the shape as a tuple, for example (5, 5) or (3, 3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

The `ones` function works in a very similar way. It creates arrays filled with ones:

In [5]:
np.ones((3, 3))  # same idea here

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

To create evenly spaced values in a given range, we can use the `linspace` function:

In [11]:
np.linspace(0, 10, 6)  # 6 values in the range 0-10, including 10

array([ 0.,  2.,  4.,  6.,  8., 10.])

The `eye` function creates an identity matrix (a square matrix) of a given size:

In [12]:
np.eye(5)  # this returns a square matrix, so we give only one size

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Using the `rand` function from NumPy's `random` module, we can create an array of a given shape with random values from a uniform distribution in the range [0, 1):

In [13]:
np.random.rand(5)  # a vector of random numbers from 0 to 1 (it does not reach 1 itself)

array([0.96189274, 0.73487489, 0.49444472, 0.57159979, 0.97587037])

In [14]:
np.random.rand(3, 2)  # the same, but now a matrix

array([[0.15035923, 0.56635759],
       [0.99309627, 0.84747083],
       [0.54918642, 0.86910955]])

The `randn` function from NumPy's `random` module is similar to `rand`. The difference is that it generates random values from the normal distribution:

In [15]:
np.random.randn(5, 5)  # similar to above, but now the distribution has mean 0 and standard deviation 1

array([[ 1.09223132,  1.01134174, -0.204271  ,  0.05773278,  1.02402038],
       [-0.18451507,  0.74529921, -1.23540266,  0.29378047,  0.54391971],
       [ 0.3021809 ,  0.41627912,  0.00390165,  0.02613831,  0.02634542],
       [-0.62427156, -1.70773967, -0.62768729,  0.20094255, -0.35074538],
       [-0.68028963,  1.20120128, -0.16436656,  0.28659376, -2.08525135]])

The `randint` function from NumPy's `random` module is also similar, but it generates random integers from a chosen range:

In [16]:
np.random.randint(1, 49, (3, 6))  # first we give the start, then the end, then the shape as a tuple (random integers)

array([[33, 33,  2, 46, 31, 17],
       [ 2,  4, 42, 26, 46,  7],
       [48,  9, 10, 17, 38, 12]])

### Indexing data in arrays

NumPy makes it easy to select values from arrays by using their positions.

In [17]:
arr_2d: np.ndarray = np.array([  # we create an example matrix from a 2D list
                               [5, 10, 15],
                               [20, 25, 30],
                               [35, 40, 45]
])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

We can get a row from such an array by giving its index:

In [18]:
arr_2d[0]  # display the first row, which has index 0

array([ 5, 10, 15])

We can get one scalar value by giving its exact position in the format `[row, column]`:

In [19]:
arr_2d[1, 2]  # here we get the value from row 1 and column 2, counting from 0

30

We can get a column from the array by selecting all rows with `:` and then giving the column index, like this: `[:, col]`:

In [20]:
arr_2d[:, 1]  # this is like choosing one cell, but : means all values in this dimension (here: all rows)

array([10, 25, 40])

Using index `-1`, we can get the last value in the chosen dimension:

In [21]:
arr_2d[-1, -1]  # -1 means the last value

45

NumPy also lets us get subarrays by using index ranges in chosen dimensions:

In [22]:
matrix: np.ndarray = np.random.randint(1, 100, (5, 5))  # create a random 5x5 matrix for later examples

matrix

array([[67, 23, 65, 72, 81],
       [46, 53, 48, 83, 48],
       [82, 26, 22, 86, 17],
       [40, 39, 22, 53, 19],
       [54, 69, 22, 93, 35]])

In [23]:
matrix[1:4, 1:4]  # choose rows with indices 1 to 3 and columns with indices 1 to 3 (4 is not included)

array([[53, 48, 83],
       [26, 22, 86],
       [39, 22, 53]])

### Shape of an array and changing it

We can check the shape of an array using the `shape` attribute:

In [24]:
arr: np.ndarray = np.ones((5, 4))  # an array of ones: 5 rows and 4 columns

print(arr)  # display the array
print(arr.shape)  # display its shape, that is: how many rows and columns it has

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


The result `(5, 4)` tells us that the matrix has 5 rows and 4 columns.

We can change the shape of an array with the `reshape` method.

In [25]:
arr: np.ndarray = np.ones(25)  # a one-dimensional array (vector) with 25 ones

arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
arr.reshape((5, 5))  # change a vector with 25 elements into a 5x5 matrix (the number of elements must stay the same)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Finding the largest and smallest values in arrays

In [27]:
arr: np.ndarray = np.random.randint(1, 100, 10)  # a vector (array) of 10 random integers from 1 to 99

arr

array([50, 74, 13, 43, 87, 58, 14, 61, 82, 51])

We can find the smallest value using the `min` method:

In [28]:
arr.min()

13

We can find the largest value using the `max` method:

In [29]:
arr.max()

87

We can find the position of the largest or smallest value using the `argmax` and `argmin` methods:

In [30]:
print(f'largest value: {arr.max()}, position of the largest value: {arr.argmax()}')  # argmax() returns the index of the largest element
print(f'smallest value: {arr.min()}, position of the smallest value: {arr.argmin()}')  # argmin() returns the index of the smallest element
# these methods are called on the array object named arr: arr.argmin(), arr.argmax(), etc.

wartosc najwieksza: 87, pozycja wartosci najwiekszej: 4
wartosc najmniejsza: 13, pozycja wartosci najmniejszej: 2


### Mathematical functions in NumPy

NumPy provides many mathematical functions that work on all elements of an array.

In [31]:
arr: np.ndarray = np.arange(11)  # create consecutive values from 0 to 10

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Using the `sqrt` function, we can calculate square roots of all elements in the array:

In [32]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

Using the `exp` function, we can calculate the value of $$e ^ x$$ where `x` is each next element of the array:

In [33]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

### Arithmetic and tensor algebra

NumPy also makes it easy to do arithmetic and algebraic operations on arrays:

In [34]:
arr0: np.ndarray = np.random.randint(1, 10, (3, 3))  # random 3x3 matrix with values from 1 to 9
arr1: np.ndarray = np.random.randint(1, 10, (3, 3))

print(arr0)  # display the first matrix
print('--------')  # separator
print(arr1)  # display the second matrix

[[2 9 5]
 [6 1 6]
 [5 1 8]]
--------
[[7 1 4]
 [7 5 8]
 [8 1 6]]


We can do arithmetic operations on arrays using standard arithmetic operators:

In [35]:
arr0 + arr1

array([[ 9, 10,  9],
       [13,  6, 14],
       [13,  2, 14]])

In [36]:
arr0 - arr1

array([[-5,  8,  1],
       [-1, -4, -2],
       [-3,  0,  2]])

In [37]:
arr0 * arr1

array([[14,  9, 20],
       [42,  5, 48],
       [40,  1, 48]])

In [38]:
arr0 ** 2

array([[ 4, 81, 25],
       [36,  1, 36],
       [25,  1, 64]])

NumPy also provides an interface for algebraic operations on tensors.
To calculate the dot product of two tensors, we can use the `dot` method:

In [39]:
arr0.dot(arr1)  # dot product of two matrices

array([[117,  52, 110],
       [ 97,  17,  68],
       [106,  18,  76]])

or similarly:

In [40]:
arr0[0].dot(arr1[1])  # dot product of the first row of matrix 1 and the second row of matrix 2

99